### ISSUE TITLE
Error during build on Ubuntu Server x64 14.04.1: make[2]: *** [CMakeFiles/npengine.dir/src/Image.cpp.o] Error 1

### ISSUE THREAD

**Issue by paxidently** [FGRE/libnpengine#9]
When I trying to build libnpengine, I get error.

Log:

```
$ cmake .
-- Configuring libnpengine version 0.5.0-98e74fd91c
-- Found NPA in /home/pax/fgre/libnpa/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pax/fgre/libnpengine
```

```
$ make
[  5%] Building CXX object CMakeFiles/npengine.dir/src/Image.cpp.o
/home/pax/fgre/libnpengine/src/Image.cpp: In member function 'void Image::LoadImage(const string&, GLenum)':
/home/pax/fgre/libnpengine/src/Image.cpp:52:65: error: 'PNG_FORMAT_GRAY' was not declared in this scope
         pPixels = LoadPNG(pData, Size, Format == GL_LUMINANCE ? PNG_FORMAT_GRAY : PNG_FORMAT_BGRA);
                                                                 ^
/home/pax/fgre/libnpengine/src/Image.cpp:52:83: error: 'PNG_FORMAT_BGRA' was not declared in this scope
         pPixels = LoadPNG(pData, Size, Format == GL_LUMINANCE ? PNG_FORMAT_GRAY : PNG_FORMAT_BGRA);
                                                                                   ^
/home/pax/fgre/libnpengine/src/Image.cpp: In member function 'uint8_t* Image::LoadPNG(uint8_t*, uint32_t, uint8_t)':
/home/pax/fgre/libnpengine/src/Image.cpp:59:5: error: 'png_image' was not declared in this scope
     png_image png;
     ^
/home/pax/fgre/libnpengine/src/Image.cpp:59:15: error: expected ';' before 'png'
     png_image png;
               ^
/home/pax/fgre/libnpengine/src/Image.cpp:60:13: error: 'png' was not declared in this scope
     memset(&png, 0, sizeof(png_image));
             ^
/home/pax/fgre/libnpengine/src/Image.cpp:61:19: error: 'PNG_IMAGE_VERSION' was not declared in this scope
     png.version = PNG_IMAGE_VERSION;
                   ^
/home/pax/fgre/libnpengine/src/Image.cpp:63:59: error: 'png_image_begin_read_from_memory' was not declared in this scope
     if (!png_image_begin_read_from_memory(&png, pMem, Size))
                                                           ^
/home/pax/fgre/libnpengine/src/Image.cpp:67:62: error: 'PNG_IMAGE_SIZE' was not declared in this scope
     uint8_t* pData = new (nothrow) uint8_t[PNG_IMAGE_SIZE(png)];
                                                              ^
/home/pax/fgre/libnpengine/src/Image.cpp:70:28: error: 'png_image_free' was not declared in this scope
         png_image_free(&png);
                            ^
/home/pax/fgre/libnpengine/src/Image.cpp:74:58: error: 'png_image_finish_read' was not declared in this scope
     if (!png_image_finish_read(&png, NULL, pData, 0, NULL))
                                                          ^
make[2]: *** [CMakeFiles/npengine.dir/src/Image.cpp.o] Error 1
make[1]: *** [CMakeFiles/npengine.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by krofna** [comment]
Ubuntu offers libpng12 at most, while FGRE uses libpng16 simplified API. You can try compiling libpng from [source](http://www.libpng.org/pub/png/libpng.html).

**Comment by krofna** [comment]
Closing this as libpng12 will not be supported
